# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information:
site_name: Business Data Science - Supervised Learning
site_url: https://github.com/fdiaz1968/ML-Course
site_author: Fernando Diaz
site_description:

# Repository
repo_name: fdiaz1968/ML-Course
repo_url: https://github.com/fdiaz1968/ML-Course
edit_uri: ''


# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed


# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# Theme
theme:
  name: material
  language: en
  logo: images/logo.bmp
  favicon: images/logo_python.svg
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fdiaz1968
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/frdiazh/
    - icon: fontawesome/solid/globe
      link: https://fralfaro.github.io/portfolio/


# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - Home: index.md
    - Program: program.md
    - Material complementario:
        - clases_asincronicas/pandas.ipynb
        - clases_asincronicas/numpy.ipynb
    - Clases sincrónicas:
        - clase0_Intro.ipynb
        - clase1_regresionlineal.ipynb
        - clase2_Resample_Methods_Bootstrapping.ipynb
        - clase3_regularizacion.ipynb
    - Clases zoom: grabaciones.md 
    - Evaluaciones: 
        - evaluacion1.md
        - evaluacion2.md


